#
# Blog Settings
#
author: Calvin A. Allen
description: My Digital Mind.
url: https://www.codingwithcalvin.net
title: Calvin A. Allen
subtitle: My Digital Mind
lang: en
timezone: America/New_York

rss_url: https://www.codingwithcalvin.net/atom.xml
gravatar_url: https://gravatar.com/avatar/a1c6325a95a54f6321b05edb40490f57
linkedin_url: https://www.linkedin.com/in/calvin-allen/
github_url: https://github.com/CalvinAllen
github_repo_url: https://github.com/calvinallen/codingwithcalvin.net
twitter_url: https://www.twitter.com/_CalvinAllen

# Disqus Comments
disqus_short_name: calvinallen
disqus_show_comment_count: true

# Jekyll Settings
permalink: /:title/
paginate: 10
paginate_path: "page/:num"
future: false

plugins:
  - jekyll-paginate
  
sass:
  sass_dir:          _scss
  style:            :compressed

exclude: ["README.md", "Gemfile", "Gemfile.lock", ".editorconfig", "rakefile.rb"]

defaults:
  -
    scope:
      path: ""
    values:
      layout: null 
      sitemap: false
      comments: false
      sharing: false
      image: null  
      image_alt: null  
  -
    scope:
      path: "page"
      type: "pages"
    values:
      layout: page 
      sitemap: true      
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      sitemap: true
      comments: true
      sharing: true
      image: "cover.png"
      image_alt: "cover.jpg"
      excerpt_separator: "<!--more-->"
      youtube: null
