#
# Blog Settings
#
author: Calvin A. Allen
description: My Digital Mind.
url: https://www.calvinallen.net
title: Calvin A. Allen
subtitle: My Digital Mind
gravatar_url: https://gravatar.com/avatar/a1c6325a95a54f6321b05edb40490f57?s=160
subscribe_rss: http://feeds.feedburner.com/CalvinAllen/
lang: en

linkedin_user: calvin-allen
stackoverflow_user: 411

# Github repositories
github_user: calvinallen
github_repo_url: https://github.com/calvinallen/calvinallen.net/

# Twitter
twitter_user: _CalvinAllen
twitter:
  username: _CalvinAllen
twitter_tweet_button: true

# Disqus Comments
disqus_short_name: calvinallen
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-48089969-1

# Jekyll Settings
permalink: /archive/:year/:month/:day/:title/
paginate: 10
paginate_path: "page/:num"
future: false

plugins:
  - jekyll-paginate
  - jekyll-postfiles
  - jekyll-redirect-from

sass:
  sass_dir:          _scss
  style:            :compressed

exclude: ["README.md", "Gemfile", "Gemfile.lock", ".editorconfig", "rakefile.rb"]

defaults:
  -
    scope:
      path: ""
    values:
      layout: null 
      sitemap: false
      comments: false
      sharing: false
      image: null  
  -
    scope:
      path: "page"
      type: "pages"
    values:
      layout: page 
      sitemap: true      
  -
    scope:
      path: "archive"
      type: "posts"
    values:
      layout: "post"
      sitemap: true
      comments: true
      sharing: true
      image: "cover.jpg"