#
# Blog Settings
#
author: Calvin A. Allen
description: My Digital Mind.
url: https://www.calvinallen.net
title: Calvin A. Allen
subtitle: My Digital Mind
lang: en
timezone: America/New_York

rss_url: https://luv2.dev/rss
gravatar_url: https://gravatar.com/avatar/a1c6325a95a54f6321b05edb40490f57
linkedin_url: https://luv2.dev/linkedin
github_url: https://luv2.dev/github
github_repo_url: https://github.com/calvinallen/calvinallen.net
stackoverflow_url: https://luv2.dev/stackoverflow
twitter_url: https://luv2.dev/twitter

# Google Analytics
google_analytics_tracking_id: UA-48089969-1

# Jekyll Settings
permalink: /:title/
paginate: 10
paginate_path: "page/:num"
future: false

plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  
sass:
  sass_dir:          _scss
  style:            :compressed

exclude: ["README.md", "Gemfile", "Gemfile.lock", ".editorconfig", "rakefile.rb"]

defaults:
  -
    scope:
      path: ""
    values:
      layout: null 
      sitemap: false
      sharing: false
      image: null  
      image_alt: null  
  -
    scope:
      path: "page"
      type: "pages"
    values:
      layout: page 
      sitemap: true      
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      sitemap: true
      sharing: true
      image: "cover.png"
      image_alt: "cover.jpg"
      excerpt_separator: "<!--more-->"
      youtube: null
