[[redirects]]
  from = "http://www.calvinallen.net/*"
  to = "https://www.codingwithcalvin.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.calvinallen.net/*"
  to = "https://www.codingwithcalvin.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://calvinallen.net/*"
  to = "https://www.codingwithcalvin.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://calvinallen.net/*"
  to = "https://www.codingwithcalvin.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.codingwithcalvin.net/docker-containers-and-my-adventures-in-tagging"
  to = "https://www.codingwithcalvin.net/docker-containers-and-my-adventures-in-versioning-and-tagging"
  status = 301
  force = true

[[redirects]]
  from = "https://www.codingwithcalvin.net/feed"
  to = "https://www.codingwithcalvin.net/atom.xml"
  status = 301
  force = true

[[redirects]]
  from = "https://www.codingwithcalvin.net/archive/2017/12/24/live-unit-testing-in-visual-studio-2017"
  to = "https://www.codingwithcalvin.net/live-unit-testing-in-visual-studio-2017"
  status = 301
  force = true
  
[[redirects]]
  from = "https://live.codingwithcalvin.net"
  to = "https://www.twitch.tv/codingwithcalvintv"
  status = 301
  force = true

[[redirects]]
  from = "https://twitch.codingwithcalvin.net"
  to = "https://www.twitch.tv/codingwithcalvintv"
  status = 301
  force = true

[[redirects]]
  from = "https://archive.codingwithcalvin.net"
  to = "https://www.youtube.com/channel/UCeh4DkPs0xLeaoDnmsGu0Og"
  status = 301
  force = true  
  
[[redirects]]
  from = "https://archives.codingwithcalvin.net"
  to = "https://www.youtube.com/channel/UCeh4DkPs0xLeaoDnmsGu0Og"
  status = 301
  force = true    
  
[[redirects]]
  from = "https://youtube.codingwithcalvin.net"
  to = "https://www.youtube.com/channel/UCeh4DkPs0xLeaoDnmsGu0Og"
  status = 301
  force = true      
