name: Jekyll Build and Deployment

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Ruby
      uses: actions/setup-ruby@v1.0.0
      with:
        version: 2.x
    - name: Build Jekyll
      run: |
        gem install bundler
        bundle install
        bundle exec jekyll build    
      
