name: Jekyll Build and Deployment

on:
  schedule:
    # 11am UTC = 7am EST (for now...stupid DST
    - cron: 0 11 * * *
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Ruby
      uses: actions/setup-ruby@v1.0.0
      with:
        version: 2.x
      
    - name: Build Jekyll
      run: |
        gem install bundler
        bundle install
        bundle exec jekyll build    
      
    - name: Upload to Azure
      uses: bacongobbler/azure-blob-storage-upload@v1.0.0
      with:
        source_dir: _site
        container_name: $web
        connection_string: ${{secrets.AZURE_BLOB_CONNECTIONSTRING}}
